/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonoyunu;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import static pokemonoyunu.İvsB.bulba;
import static pokemonoyunu.İvsB.butter;
import static pokemonoyunu.İvsB.charm;
import static pokemonoyunu.İvsB.jiggly;
import static pokemonoyunu.İvsB.meow;
import static pokemonoyunu.İvsB.pc1;
import static pokemonoyunu.İvsB.pc2;
import static pokemonoyunu.İvsB.pika;
import static pokemonoyunu.İvsB.psy;
import static pokemonoyunu.İvsB.snor;
import static pokemonoyunu.İvsB.squirt;
import static pokemonoyunu.İvsB.zuba;

/**
 *
 * @author İlker
 */
public class BvsB extends javax.swing.JFrame {

     static Pikachu pika=new  Pikachu("1","Pikachu","Elektrik");
        static Bulbasaur bulba=new Bulbasaur("2","Bulbasaur","Çim");
        static Charmander charm=new Charmander("3","Charmander","Ateş");
        static Squirtle squirt=new Squirtle("4","Squirtle","Su");
        static Zubat zuba=new Zubat("5","Zubat","Hava");
        static Psyduck psy=new Psyduck("6","Psyduck","Su");
        static Snorlax snor=new Snorlax("7","Snorlax","Normal");
        static Butterfree butter=new Butterfree("8","Butterfree","Hava");
        static Jigglypuff jiggly=new Jigglypuff("9","Jigglypuff","Ses");
        static Meowth meow=new Meowth("10","Meowth","Normal");
       static BilgisayarOyuncusu pc2=new BilgisayarOyuncusu(2,"pc2");
       static BilgisayarOyuncusu pc1=new BilgisayarOyuncusu(1,"pc1");
         ArrayList<Pokemon> list=new ArrayList<Pokemon>();
         ArrayList<Integer> hasar=new ArrayList<Integer>();
         ArrayList<Integer> hasar1=new ArrayList<Integer>();
    public BvsB() {
        list.add(pika);
        list.add(bulba);
        list.add(charm);
        list.add(squirt);
        list.add(zuba);
        list.add(psy);
        list.add(snor);
        list.add(butter);
        list.add(jiggly);
        list.add(meow);
         int t1,t2,t3,a;
        t1=1;t2=1;t3=1;
        a=pc1.kartSecim(t1, t2, t3);
        Random rnd=new Random();
        while(t1==t2 || t1==t3 || t2==t3){
        t1=rnd.nextInt(10);
        t2=rnd.nextInt(10);
        t3=rnd.nextInt(10);
        }
        int t4=1,t5=1,t6=1,t7=1,t8=1,t9=1,t10=1;
        while(t1==t4 || t1==t5 || t2==t6 || t2==t5 || t1==t6 || t2==t4 || t3==t4
              || t3==t5 || t3==t6 || t4==t5 || t4==t6 || t5==t6){
        t4=rnd.nextInt(10);
        t5=rnd.nextInt(10);
        t6=rnd.nextInt(10);
        }
         while(t7==t1||t7==t2||t7==t3||t7==t3||t7==t4||t7==t5||t7==t6||t8==t1
                 ||t8==t2||t8==t3||t8==t4||t8==t5||t8==t6||t9==t1||t9==t2
                 ||t9==t3||t9==t4||t9==t5||t9==t6||t10==t1||t10==t2||t10==t3
                 ||t10==t4||t10==t5||t10==t6||t7==t8||t7==t9||t7==t10||t8==t9
                 ||t8==t10||t9==t10)
         {
          t7=rnd.nextInt(10);
        t8=rnd.nextInt(10);
        t9=rnd.nextInt(10);
         t10=rnd.nextInt(10);}
      pc1.setSecim1(t1);
      pc1.setSecim2(t2);
      pc1.setSecim3(t3);
      pc2.setSecim1(t4);
      pc2.setSecim2(t5);
      pc2.setSecim3(t6);
      pc1.setSecim4(t7);
      pc1.setSecim5(t8);
      pc2.setSecim4(t9);
      pc2.setSecim5(t10);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 720, 190, 220);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 720, 190, 220);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(750, 720, 190, 220);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(140, 50, 190, 220);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(500, 50, 190, 220);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(840, 60, 190, 220);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1170, 590, 190, 220);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1400, 590, 190, 220);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(1160, 320, 190, 220);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(1400, 320, 190, 220);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(500, 50, 190, 220);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(840, 60, 190, 220);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/choosen.jpg"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(330, 440, 190, 220);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/choosen.jpg"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(620, 360, 190, 220);

        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(430, 720, 190, 220);

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(750, 720, 190, 220);

        jButton17.setText("SKORU GÖR");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(1260, 80, 190, 40);

        s1.setEditable(false);
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1);
        s1.setBounds(1230, 190, 240, 40);

        s2.setEditable(false);
        getContentPane().add(s2);
        s2.setBounds(1230, 130, 240, 40);

        jTextField1.setEditable(false);
        jTextField1.setText("                                        PC2");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(470, 0, 250, 40);

        jTextField2.setEditable(false);
        jTextField2.setText("                                        PC1");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(400, 960, 250, 40);

        jButton18.setText("OYUNU BAŞLAT");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(1260, 20, 180, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FightBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 1920, 1090);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ImageIcon icon = new ImageIcon(list.get(pc1.secim2).getDosyaYolu());
        jButton2.setIcon(icon);
        jButton13.setIcon(icon);
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton1.setIcon(icon2);
        jButton3.setIcon(icon2);
        jButton2.setVisible(false);
        hasar.add((list.get(pc1.secim2)).getHasar());
        jButton15.setVisible(false);
        jButton5.doClick();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImageIcon icon = new ImageIcon(list.get(pc1.secim1).getDosyaYolu());
        jButton1.setIcon(icon);
        jButton13.setIcon(icon);
        
        
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton2.setIcon(icon2);
        jButton3.setIcon(icon2);
        jButton1.setVisible(false);
        hasar.add((list.get(pc1.secim1)).getHasar());
        jButton4.doClick();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ImageIcon icon = new ImageIcon(list.get(pc1.secim3).getDosyaYolu());
        jButton3.setIcon(icon);
        jButton13.setIcon(icon);
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton2.setIcon(icon2);
        jButton1.setIcon(icon2);
        jButton3.setVisible(false);
        hasar.add((list.get(pc1.secim3)).getHasar());
        jButton16.setVisible(false);
        jButton6.doClick();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ImageIcon icon = new ImageIcon(list.get(pc2.secim1).getDosyaYolu());
        jButton4.setIcon(icon);
        jButton14.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton5.setIcon(icon2);
        jButton6.setIcon(icon2);
        jButton4.setVisible(false);
        hasar1.add((list.get(pc2.secim1)).getHasar());
        jButton2.doClick();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ImageIcon icon = new ImageIcon(list.get(pc2.secim3).getDosyaYolu());
        jButton6.setIcon(icon);
        jButton14.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton5.setIcon(icon2);
        jButton4.setIcon(icon2);
        jButton6.setVisible(false);
        hasar1.add((list.get(pc2.secim3)).getHasar());
        jButton12.setVisible(false);
        jButton7.doClick();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           ImageIcon icon = new ImageIcon(list.get(pc2.secim2).getDosyaYolu());
    
        //jButton5.setIcon(icon);
        jButton14.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton6.setIcon(icon2);
        jButton4.setIcon(icon2);
        jButton5.setVisible(false);
        hasar1.add((list.get(pc2.secim2)).getHasar());
        jButton11.setVisible(false);
        jButton3.doClick();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setVisible(false);
    ImageIcon icon = new ImageIcon(list.get(pc1.secim4).getDosyaYolu());
    
        jButton15.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton15.setIcon(icon2);
        jButton15.setVisible(true);
        jButton9.doClick();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         ImageIcon icon = new ImageIcon(list.get(pc1.secim5).getDosyaYolu());
    jButton8.setVisible(false);
    jButton16.setIcon(icon);   
     ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton16.setIcon(icon2);
        jButton16.setVisible(true);
    jButton10.doClick();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         jButton9.setVisible(false);
    ImageIcon icon = new ImageIcon(list.get(pc2.secim4).getDosyaYolu());
    
        jButton11.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton11.setIcon(icon2);
        jButton11.setVisible(true);
        jButton8.doClick();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         jButton10.setVisible(false);
    ImageIcon icon = new ImageIcon(list.get(pc2.secim5).getDosyaYolu());
    
        jButton12.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton12.setIcon(icon2);
        jButton12.setVisible(true);
        jButton15.doClick();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       ImageIcon icon = new ImageIcon(list.get(pc2.secim4).getDosyaYolu());
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton11.setIcon(icon2);
        jButton14.setIcon(icon);  
        jButton11.setVisible(false);
        hasar1.add(list.get(pc2.secim4).getHasar());
        jButton16.doClick();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       ImageIcon icon = new ImageIcon(list.get(pc2.secim5).getDosyaYolu());
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton12.setIcon(icon2);
        jButton14.setIcon(icon);  
        jButton12.setVisible(false);
        hasar1.add(list.get(pc2.secim5).getHasar());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
           ImageIcon icon = new ImageIcon(list.get(pc1.secim4).getDosyaYolu());
    
        jButton13.setIcon(icon);
        //jButton1.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        //button5.setVisible(false);
        jButton15.setVisible(false);
         hasar.add(list.get(pc1.secim4).getHasar());
         jButton11.doClick();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
           ImageIcon icon = new ImageIcon(list.get(pc1.secim4).getDosyaYolu());
    
        jButton13.setIcon(icon);
        //jButton1.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        //button5.setVisible(false);
        jButton16.setVisible(false);
         hasar.add(list.get(pc1.secim4).getHasar());
         jButton12.doClick();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
             if(hasar.get(0)>hasar1.get(0))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(1)>hasar1.get(1))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(2)>hasar1.get(2))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(3)>hasar1.get(3))
            pc1.skor=pc1.skor+5;
        else
{pc2.skor=pc2.skor+5;}
if(hasar.get(4)>hasar1.get(4))
            pc1.skor=pc1.skor+5;
else{
        pc2.skor=pc2.skor+5;}
s1.setText("PC1:  "+pc1.skor);
s2.setText("PC2:  "+pc2.skor);
if(pc1.skor>pc2.skor)s1.setText("PC1:  "+pc1.skor+"   KAZANAN PC1");
else s2.setText("PC1:  "+pc2.skor+"   KAZANAN PC2");

    }//GEN-LAST:event_jButton17ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BvsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BvsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BvsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BvsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BvsB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    // End of variables declaration//GEN-END:variables
}
