/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonoyunu;


import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
/**
 *
 * @author İlker
 */
public class İvsB extends javax.swing.JFrame {
   
        static Pikachu pika=new  Pikachu("1","Pikachu","Elektrik");
        static Bulbasaur bulba=new Bulbasaur("2","Bulbasaur","Çim");
        static Charmander charm=new Charmander("3","Charmander","Ateş");
        static Squirtle squirt=new Squirtle("4","Squirtle","Su");
        static Zubat zuba=new Zubat("5","Zubat","Hava");
        static Psyduck psy=new Psyduck("6","Psyduck","Su");
        static Snorlax snor=new Snorlax("7","Snorlax","Normal");
        static Butterfree butter=new Butterfree("8","Butterfree","Hava");
        static Jigglypuff jiggly=new Jigglypuff("9","Jigglypuff","Ses");
        static Meowth meow=new Meowth("10","Meowth","Normal");
       static BilgisayarOyuncusu pc2=new BilgisayarOyuncusu(2,"pc2");
       static BilgisayarOyuncusu pc1=new BilgisayarOyuncusu(1,"pc1");
         ArrayList<Pokemon> list=new ArrayList<Pokemon>();
         ArrayList<Integer> hasar=new ArrayList<Integer>();
         ArrayList<Integer> hasar1=new ArrayList<Integer>();

    /**
     * Creates new form BvsB
     */
    public İvsB() {
        
        list.add(pika);
        list.add(bulba);
        list.add(charm);
        list.add(squirt);
        list.add(zuba);
        list.add(psy);
        list.add(snor);
        list.add(butter);
        list.add(jiggly);
        list.add(meow);
         int t1,t2,t3,a;
        t1=1;t2=1;t3=1;
        a=pc1.kartSecim(t1, t2, t3);
        Random rnd=new Random();
        while(t1==t2 || t1==t3 || t2==t3){
        t1=rnd.nextInt(10);
        t2=rnd.nextInt(10);
        t3=rnd.nextInt(10);
        }
        int t4=1,t5=1,t6=1,t7=1,t8=1,t9=1,t10=1;
        while(t1==t4 || t1==t5 || t2==t6 || t2==t5 || t1==t6 || t2==t4 || t3==t4
              || t3==t5 || t3==t6 || t4==t5 || t4==t6 || t5==t6){
        t4=rnd.nextInt(10);
        t5=rnd.nextInt(10);
        t6=rnd.nextInt(10);
        }
         while(t7==t1||t7==t2||t7==t3||t7==t3||t7==t4||t7==t5||t7==t6||t8==t1
                 ||t8==t2||t8==t3||t8==t4||t8==t5||t8==t6||t9==t1||t9==t2
                 ||t9==t3||t9==t4||t9==t5||t9==t6||t10==t1||t10==t2||t10==t3
                 ||t10==t4||t10==t5||t10==t6||t7==t8||t7==t9||t7==t10||t8==t9
                 ||t8==t10||t9==t10)
         {
          t7=rnd.nextInt(10);
        t8=rnd.nextInt(10);
        t9=rnd.nextInt(10);
         t10=rnd.nextInt(10);}
      pc1.setSecim1(t1);
      pc1.setSecim2(t2);
      pc1.setSecim3(t3);
      pc2.setSecim1(t4);
      pc2.setSecim2(t5);
      pc2.setSecim3(t6);
      pc1.setSecim4(t7);
      pc1.setSecim5(t8);
      pc2.setSecim4(t9);
      pc2.setSecim5(t10);
        System.out.println(t1+""+t2+""+t3+""+t4+""+t5+""+t6+""+t7+""+t8+""+t9+""+t10);
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button1 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Skor = new javax.swing.JButton();
        pc1skor = new javax.swing.JTextField();
        pc2skor = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1);
        Button1.setBounds(60, 730, 210, 250);

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4);
        button4.setBounds(60, 30, 210, 240);

        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6);
        button6.setBounds(630, 30, 210, 240);

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5);
        button5.setBounds(340, 30, 220, 240);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(370, 730, 220, 250);

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3);
        button3.setBounds(660, 730, 210, 250);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/choosen.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 310, 220, 270);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1010, 270, 220, 220);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1250, 270, 220, 220);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1250, 500, 210, 240);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CardBack.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1010, 500, 221, 240);

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(370, 730, 220, 250);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(660, 730, 210, 250);

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(340, 30, 220, 240);

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(630, 30, 210, 240);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/choosen.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 440, 220, 270);

        Skor.setText("SKORU GÖR");
        Skor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkorActionPerformed(evt);
            }
        });
        getContentPane().add(Skor);
        Skor.setBounds(990, 20, 290, 90);

        pc1skor.setEditable(false);
        getContentPane().add(pc1skor);
        pc1skor.setBounds(930, 190, 400, 40);

        pc2skor.setEditable(false);
        getContentPane().add(pc2skor);
        pc2skor.setBounds(930, 130, 400, 40);

        jTextField1.setEditable(false);
        jTextField1.setText("     PC1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(460, 0, 41, 20);

        jTextField2.setEditable(false);
        jTextField2.setText("      İLKER");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(440, 990, 53, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FightBackground.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1920, 1110);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
       
        ImageIcon icon = new ImageIcon(list.get(pc2.secim2).getDosyaYolu());
    
        button5.setIcon(icon);
        jButton2.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        button6.setIcon(icon2);
        button4.setIcon(icon2);
        button5.setVisible(false);
        hasar1.add((list.get(pc2.secim2)).getHasar());
        jButton10.setVisible(false);
      
    }//GEN-LAST:event_button5ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
     ImageIcon icon = new ImageIcon(list.get(pc1.secim1).getDosyaYolu());
        jButton1.setIcon(icon);
        Button1.setIcon(icon);
        
        
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        button2.setIcon(icon2);
        button3.setIcon(icon2);
        Button1.setVisible(false);
        hasar.add((list.get(pc1.secim1)).getHasar());
        button4.doClick();
    }//GEN-LAST:event_Button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
   ImageIcon icon = new ImageIcon(list.get(pc1.secim2).getDosyaYolu());
        button2.setIcon(icon);
        jButton1.setIcon(icon);
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        Button1.setIcon(icon2);
        button3.setIcon(icon2);
        button2.setVisible(false);
        hasar.add((list.get(pc1.secim2)).getHasar());
        jButton8.setVisible(false);
        button5.doClick();
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
ImageIcon icon = new ImageIcon(list.get(pc1.secim3).getDosyaYolu());
        button3.setIcon(icon);
        jButton1.setIcon(icon);
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        button2.setIcon(icon2);
        Button1.setIcon(icon2);
        button3.setVisible(false);
        hasar.add((list.get(pc1.secim3)).getHasar());
        jButton9.setVisible(false);
        button6.doClick();
        
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        ImageIcon icon = new ImageIcon(list.get(pc2.secim1).getDosyaYolu());
        button4.setIcon(icon);
        jButton2.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        button5.setIcon(icon2);
        button6.setIcon(icon2);
        button4.setVisible(false);
        hasar1.add((list.get(pc2.secim1)).getHasar());
    }//GEN-LAST:event_button4ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
       ImageIcon icon = new ImageIcon(list.get(pc2.secim3).getDosyaYolu());
        button6.setIcon(icon);
        jButton2.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        button5.setIcon(icon2);
        button4.setIcon(icon2);
        button6.setVisible(false);
        hasar1.add((list.get(pc2.secim3)).getHasar());
        jButton11.setVisible(false);
    }//GEN-LAST:event_button6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setVisible(false);
    ImageIcon icon = new ImageIcon(list.get(pc2.secim4).getDosyaYolu());
    
        jButton10.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton10.setIcon(icon2);
        jButton10.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     jButton5.setVisible(false);
    ImageIcon icon = new ImageIcon(list.get(pc1.secim4).getDosyaYolu());
    
        jButton8.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton8.setIcon(icon2);
        jButton8.setVisible(true);
        jButton3.doClick();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    ImageIcon icon = new ImageIcon(list.get(pc1.secim5).getDosyaYolu());
    jButton6.setVisible(false);
    jButton9.setIcon(icon);   
     ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton9.setIcon(icon2);
        jButton9.setVisible(true);
    jButton4.doClick();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jButton4.setVisible(false);
    ImageIcon icon = new ImageIcon(list.get(pc2.secim5).getDosyaYolu());
    
        jButton11.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton11.setIcon(icon2);
        jButton11.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(hasar.get(0)>hasar1.get(0))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(1)>hasar1.get(1))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(2)>hasar1.get(2))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(3)>hasar1.get(3))
            pc1.skor=pc1.skor+5;
        else
{pc2.skor=pc2.skor+5;}
if(hasar.get(4)>hasar1.get(4))
            pc1.skor=pc1.skor+5;
else{
        pc2.skor=pc2.skor+5;}
        System.out.println(pc1.skor);
        System.out.println(pc2.skor);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       ImageIcon icon = new ImageIcon(list.get(pc1.secim5).getDosyaYolu());
        jButton1.setIcon(icon);  
        
         jButton9.setVisible(false);
        hasar.add((list.get(pc1.secim5)).getHasar());
        jButton11.doClick();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
   ImageIcon icon = new ImageIcon(list.get(pc1.secim4).getDosyaYolu());
    
        jButton8.setIcon(icon);
        jButton1.setIcon(icon);
         ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        button5.setVisible(false);
        jButton8.setVisible(false);
         hasar.add(list.get(pc1.secim4).getHasar());
         jButton10.doClick();
        
        
     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        ImageIcon icon = new ImageIcon(list.get(pc2.secim4).getDosyaYolu());
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton10.setIcon(icon2);
        jButton2.setIcon(icon);  
        jButton10.setVisible(false);
        hasar1.add(list.get(pc2.secim4).getHasar());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        ImageIcon icon = new ImageIcon(list.get(pc2.secim5).getDosyaYolu());
        ImageIcon icon2 = new ImageIcon("src//image//CardBack.jpg");
        jButton11.setIcon(icon2);
        jButton2.setIcon(icon);  
        jButton11.setVisible(false);
        hasar1.add(list.get(pc2.secim5).getHasar());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void SkorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkorActionPerformed
        if(hasar.get(0)>hasar1.get(0))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(1)>hasar1.get(1))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(2)>hasar1.get(2))
            pc1.skor=pc1.skor+5;
        else
        pc2.skor=pc2.skor+5;
if(hasar.get(3)>hasar1.get(3))
            pc1.skor=pc1.skor+5;
        else
{pc2.skor=pc2.skor+5;}
if(hasar.get(4)>hasar1.get(4))
            pc1.skor=pc1.skor+5;
else{
        pc2.skor=pc2.skor+5;}
        System.out.println(pc1.skor);
        System.out.println(pc2.skor);
        pc1skor.setText("İLKER"+" : "+  pc1.skor);
        pc2skor.setText(pc1.oyuncuAdi+" : "+  pc2.skor);
        if(pc1.skor>pc2.skor)
        pc1skor.setText("İLKER"+" : "+  pc1.skor+"  "+"İLKER"+" KAZANDI");
        else
            pc2skor.setText(pc2.oyuncuAdi+" : "+  pc2.skor+"  "+pc1.oyuncuAdi+" KAZANDI");
    }//GEN-LAST:event_SkorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ArrayList<Pokemon> list=new ArrayList<Pokemon>();
       
       
     
     // pc1.kartSecim(t1, t2, t3);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(İvsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(İvsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(İvsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(İvsB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new İvsB().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Skor;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField pc1skor;
    private javax.swing.JTextField pc2skor;
    // End of variables declaration//GEN-END:variables
}
